# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About Tabbre
    url: about
    weight: 10
  - name: Road Map
    url: roadmap
    weight: 20
  - name: People
    url: pages/roadmap
    weight: 30
  - name: Contributing
    url: pages/roadmap
    weight: 40
  - name: FAQs
    url: pages/roadmap
    weight: 50
  - name: More Information
    url: pages/roadmap
    weight: 60
  - name: Blog
    url: blog
    weight: 70
  - name: Contact us
    url: pages/roadmap
    weight: 80
